name: Update Server

on:
  push:
    branches:
      - 2023
  workflow_dispatch:

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Update Server
        env:
          SSH_USER: 'administrator'
          SERVER_IP: 'nebulouscereal.com'
        run: |
          set -x
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh $SSH_USER@$SERVER_IP "cd /home/administrator/BetterSNS-api/ && git pull && ./update_script.sh"
